spring.application.name=backend
server.port=${PORT:8080}
# Actuator for health checks
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

#MongoDB configuration
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
#Email configuration
spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.from=${SPRING_MAIL_FROM}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp

#Application info
app.base.url=${APP_BASE_URL}

#Cloudinary configuration
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}

#Jwt configuration
jwt.secret=this-is-going-to-be-very-long-string-for-jwt-token-bilsan-haddle-this
jwt.expiration=604800000

#Razorpay configuration
razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}

#Frontend Url
frontend.url=${FRONTEND_URL}


# File Upload Limits
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
